### ISSUE TITLE
Cannot import pandas

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/assign-reviewers#1]
I am getting this:
~~~
>>> import pandas
Traceback (most recent call last):
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from .conversion import OutOfBoundsTimedelta, localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 14, in init pandas._libs.tslibs.timezones
ModuleNotFoundError: No module named 'pytz.tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/pandas/__init__.py", line 37, in <module>
    ) from e
ImportError: C extension: No module named 'pytz.tzinfo' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --force' to build the C extensions first.
~~~

**Comment by jcohenadad** [comment]
One way to solve this was to work under a clean venv, using https://virtualenv.pypa.io/en/latest/user_guide.html
